// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "video_player_avfoundation",
    platforms: [
        .iOS("13.0")
    ],
    products: [
        .library(name: "video-player-avfoundation", targets: ["video_player_avfoundation"])
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework")
    ],
    targets: [
        .target(
            name: "video_player_avfoundation",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework")
            ],
            resources: [
                .process("Resources")
            ],
            cSettings: [
                // Lets code regenerated by Pigeon (which imports "messages.g.h" by
                // file name) resolve its header.
                .headerSearchPath("include/video_player_avfoundation")
            ]
        )
    ]
)
