// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "./include/video_player_avfoundation/messages.g.h"

#if TARGET_OS_OSX
@import FlutterMacOS;
#else
@import Flutter;
#endif

static BOOL __attribute__((unused)) FLTPigeonDeepEquals(id _Nullable a, id _Nullable b) {
  if (a == b) {
    return YES;
  }
  if (a == nil) {
    return b == [NSNull null];
  }
  if (b == nil) {
    return a == [NSNull null];
  }
  if ([a isKindOfClass:[NSNumber class]] && [b isKindOfClass:[NSNumber class]]) {
    return [a isEqual:b] || (isnan([(NSNumber *)a doubleValue]) && isnan([(NSNumber *)b doubleValue]));
  }
  if ([a isKindOfClass:[NSArray class]] && [b isKindOfClass:[NSArray class]]) {
    NSArray *arrayA = (NSArray *)a;
    NSArray *arrayB = (NSArray *)b;
    if (arrayA.count != arrayB.count) {
      return NO;
    }
    for (NSUInteger i = 0; i < arrayA.count; i++) {
      if (!FLTPigeonDeepEquals(arrayA[i], arrayB[i])) {
        return NO;
      }
    }
    return YES;
  }
  if ([a isKindOfClass:[NSDictionary class]] && [b isKindOfClass:[NSDictionary class]]) {
    NSDictionary *dictA = (NSDictionary *)a;
    NSDictionary *dictB = (NSDictionary *)b;
    if (dictA.count != dictB.count) {
      return NO;
    }
    for (id keyA in dictA) {
      id valueA = dictA[keyA];
      BOOL found = NO;
      for (id keyB in dictB) {
        if (FLTPigeonDeepEquals(keyA, keyB)) {
          id valueB = dictB[keyB];
          if (FLTPigeonDeepEquals(valueA, valueB)) {
            found = YES;
            break;
          } else {
            return NO;
          }
        }
      }
      if (!found) {
        return NO;
      }
    }
    return YES;
  }
  return [a isEqual:b];
}

static NSUInteger __attribute__((unused)) FLTPigeonDeepHash(id _Nullable value) {
  if (value == nil || value == (id)[NSNull null]) {
    return 0;
  }
  if ([value isKindOfClass:[NSNumber class]]) {
    NSNumber *n = (NSNumber *)value;
    double d = n.doubleValue;
    if (isnan(d)) {
      // Normalize NaN to a consistent hash.
      return (NSUInteger)0x7FF8000000000000;
    }
    if (d == 0.0) {
      // Normalize -0.0 to 0.0 so they have the same hash code.
      d = 0.0;
    }
    return @(d).hash;
  }
  if ([value isKindOfClass:[NSArray class]]) {
    NSUInteger result = 1;
    for (id item in (NSArray *)value) {
      result = result * 31 + FLTPigeonDeepHash(item);
    }
    return result;
  }
  if ([value isKindOfClass:[NSDictionary class]]) {
    NSUInteger result = 0;
    NSDictionary *dict = (NSDictionary *)value;
    for (id key in dict) {
      result += ((FLTPigeonDeepHash(key) * 31) ^ FLTPigeonDeepHash(dict[key]));
    }
    return result;
  }
  return [value hash];
}


static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface FLTTextureMessage ()
+ (FLTTextureMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTTextureMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTLoopingMessage ()
+ (FLTLoopingMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTLoopingMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTVolumeMessage ()
+ (FLTVolumeMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTVolumeMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTPlaybackSpeedMessage ()
+ (FLTPlaybackSpeedMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTPlaybackSpeedMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTPositionMessage ()
+ (FLTPositionMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTPositionMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTDurationMessage ()
+ (FLTDurationMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTDurationMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTStartMessage ()
+ (FLTStartMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTStartMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTCreateMessage ()
+ (FLTCreateMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTCreateMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTMixWithOthersMessage ()
+ (FLTMixWithOthersMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTMixWithOthersMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTBufferMessage ()
+ (FLTBufferMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTBufferMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTMaxVideoResolutionMessage ()
+ (FLTMaxVideoResolutionMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTMaxVideoResolutionMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTIsPlayingMessage ()
+ (FLTIsPlayingMessage *)fromList:(NSArray<id> *)list;
+ (nullable FLTIsPlayingMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation FLTTextureMessage
+ (instancetype)makeWithTextureId:(NSInteger )textureId {
  FLTTextureMessage* pigeonResult = [[FLTTextureMessage alloc] init];
  pigeonResult.textureId = textureId;
  return pigeonResult;
}
+ (FLTTextureMessage *)fromList:(NSArray<id> *)list {
  FLTTextureMessage *pigeonResult = [[FLTTextureMessage alloc] init];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 0) integerValue];
  return pigeonResult;
}
+ (nullable FLTTextureMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTTextureMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.textureId),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTTextureMessage *other = (FLTTextureMessage *)object;
  return self.textureId == other.textureId;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.textureId).hash;
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTTextureMessage(textureId: %ld)", (long)self.textureId];
}
@end

@implementation FLTLoopingMessage
+ (instancetype)makeWithTextureId:(NSInteger )textureId
    isLooping:(BOOL )isLooping {
  FLTLoopingMessage* pigeonResult = [[FLTLoopingMessage alloc] init];
  pigeonResult.textureId = textureId;
  pigeonResult.isLooping = isLooping;
  return pigeonResult;
}
+ (FLTLoopingMessage *)fromList:(NSArray<id> *)list {
  FLTLoopingMessage *pigeonResult = [[FLTLoopingMessage alloc] init];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.isLooping = [GetNullableObjectAtIndex(list, 1) boolValue];
  return pigeonResult;
}
+ (nullable FLTLoopingMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTLoopingMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.textureId),
    @(self.isLooping),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTLoopingMessage *other = (FLTLoopingMessage *)object;
  return self.textureId == other.textureId && self.isLooping == other.isLooping;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.textureId).hash;
  result = result * 31 + @(self.isLooping).hash;
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTLoopingMessage(textureId: %ld, isLooping: %@)", (long)self.textureId, self.isLooping ? @"true" : @"false"];
}
@end

@implementation FLTVolumeMessage
+ (instancetype)makeWithTextureId:(NSInteger )textureId
    volume:(double )volume {
  FLTVolumeMessage* pigeonResult = [[FLTVolumeMessage alloc] init];
  pigeonResult.textureId = textureId;
  pigeonResult.volume = volume;
  return pigeonResult;
}
+ (FLTVolumeMessage *)fromList:(NSArray<id> *)list {
  FLTVolumeMessage *pigeonResult = [[FLTVolumeMessage alloc] init];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.volume = [GetNullableObjectAtIndex(list, 1) doubleValue];
  return pigeonResult;
}
+ (nullable FLTVolumeMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTVolumeMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.textureId),
    @(self.volume),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTVolumeMessage *other = (FLTVolumeMessage *)object;
  return self.textureId == other.textureId && (self.volume == other.volume || (isnan(self.volume) && isnan(other.volume)));
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.textureId).hash;
  result = result * 31 + (isnan(self.volume) ? (NSUInteger)0x7FF8000000000000 : @(self.volume).hash);
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTVolumeMessage(textureId: %ld, volume: %f)", (long)self.textureId, self.volume];
}
@end

@implementation FLTPlaybackSpeedMessage
+ (instancetype)makeWithTextureId:(NSInteger )textureId
    speed:(double )speed {
  FLTPlaybackSpeedMessage* pigeonResult = [[FLTPlaybackSpeedMessage alloc] init];
  pigeonResult.textureId = textureId;
  pigeonResult.speed = speed;
  return pigeonResult;
}
+ (FLTPlaybackSpeedMessage *)fromList:(NSArray<id> *)list {
  FLTPlaybackSpeedMessage *pigeonResult = [[FLTPlaybackSpeedMessage alloc] init];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.speed = [GetNullableObjectAtIndex(list, 1) doubleValue];
  return pigeonResult;
}
+ (nullable FLTPlaybackSpeedMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTPlaybackSpeedMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.textureId),
    @(self.speed),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTPlaybackSpeedMessage *other = (FLTPlaybackSpeedMessage *)object;
  return self.textureId == other.textureId && (self.speed == other.speed || (isnan(self.speed) && isnan(other.speed)));
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.textureId).hash;
  result = result * 31 + (isnan(self.speed) ? (NSUInteger)0x7FF8000000000000 : @(self.speed).hash);
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTPlaybackSpeedMessage(textureId: %ld, speed: %f)", (long)self.textureId, self.speed];
}
@end

@implementation FLTPositionMessage
+ (instancetype)makeWithTextureId:(NSInteger )textureId
    position:(NSInteger )position {
  FLTPositionMessage* pigeonResult = [[FLTPositionMessage alloc] init];
  pigeonResult.textureId = textureId;
  pigeonResult.position = position;
  return pigeonResult;
}
+ (FLTPositionMessage *)fromList:(NSArray<id> *)list {
  FLTPositionMessage *pigeonResult = [[FLTPositionMessage alloc] init];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.position = [GetNullableObjectAtIndex(list, 1) integerValue];
  return pigeonResult;
}
+ (nullable FLTPositionMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTPositionMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.textureId),
    @(self.position),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTPositionMessage *other = (FLTPositionMessage *)object;
  return self.textureId == other.textureId && self.position == other.position;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.textureId).hash;
  result = result * 31 + @(self.position).hash;
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTPositionMessage(textureId: %ld, position: %ld)", (long)self.textureId, (long)self.position];
}
@end

@implementation FLTDurationMessage
+ (instancetype)makeWithTextureId:(NSInteger )textureId
    duration:(NSInteger )duration {
  FLTDurationMessage* pigeonResult = [[FLTDurationMessage alloc] init];
  pigeonResult.textureId = textureId;
  pigeonResult.duration = duration;
  return pigeonResult;
}
+ (FLTDurationMessage *)fromList:(NSArray<id> *)list {
  FLTDurationMessage *pigeonResult = [[FLTDurationMessage alloc] init];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.duration = [GetNullableObjectAtIndex(list, 1) integerValue];
  return pigeonResult;
}
+ (nullable FLTDurationMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTDurationMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.textureId),
    @(self.duration),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTDurationMessage *other = (FLTDurationMessage *)object;
  return self.textureId == other.textureId && self.duration == other.duration;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.textureId).hash;
  result = result * 31 + @(self.duration).hash;
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTDurationMessage(textureId: %ld, duration: %ld)", (long)self.textureId, (long)self.duration];
}
@end

@implementation FLTStartMessage
+ (instancetype)makeWithTextureId:(NSInteger )textureId
    start:(NSInteger )start {
  FLTStartMessage* pigeonResult = [[FLTStartMessage alloc] init];
  pigeonResult.textureId = textureId;
  pigeonResult.start = start;
  return pigeonResult;
}
+ (FLTStartMessage *)fromList:(NSArray<id> *)list {
  FLTStartMessage *pigeonResult = [[FLTStartMessage alloc] init];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.start = [GetNullableObjectAtIndex(list, 1) integerValue];
  return pigeonResult;
}
+ (nullable FLTStartMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTStartMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.textureId),
    @(self.start),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTStartMessage *other = (FLTStartMessage *)object;
  return self.textureId == other.textureId && self.start == other.start;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.textureId).hash;
  result = result * 31 + @(self.start).hash;
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTStartMessage(textureId: %ld, start: %ld)", (long)self.textureId, (long)self.start];
}
@end

@implementation FLTCreateMessage
+ (instancetype)makeWithAsset:(nullable NSString *)asset
    uri:(nullable NSString *)uri
    packageName:(nullable NSString *)packageName
    formatHint:(nullable NSString *)formatHint
    httpHeaders:(NSDictionary<NSString *, NSString *> *)httpHeaders {
  FLTCreateMessage* pigeonResult = [[FLTCreateMessage alloc] init];
  pigeonResult.asset = asset;
  pigeonResult.uri = uri;
  pigeonResult.packageName = packageName;
  pigeonResult.formatHint = formatHint;
  pigeonResult.httpHeaders = httpHeaders;
  return pigeonResult;
}
+ (FLTCreateMessage *)fromList:(NSArray<id> *)list {
  FLTCreateMessage *pigeonResult = [[FLTCreateMessage alloc] init];
  pigeonResult.asset = GetNullableObjectAtIndex(list, 0);
  pigeonResult.uri = GetNullableObjectAtIndex(list, 1);
  pigeonResult.packageName = GetNullableObjectAtIndex(list, 2);
  pigeonResult.formatHint = GetNullableObjectAtIndex(list, 3);
  pigeonResult.httpHeaders = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable FLTCreateMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTCreateMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.asset ?: [NSNull null],
    self.uri ?: [NSNull null],
    self.packageName ?: [NSNull null],
    self.formatHint ?: [NSNull null],
    self.httpHeaders ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTCreateMessage *other = (FLTCreateMessage *)object;
  return FLTPigeonDeepEquals(self.asset, other.asset) && FLTPigeonDeepEquals(self.uri, other.uri) && FLTPigeonDeepEquals(self.packageName, other.packageName) && FLTPigeonDeepEquals(self.formatHint, other.formatHint) && FLTPigeonDeepEquals(self.httpHeaders, other.httpHeaders);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.asset);
  result = result * 31 + FLTPigeonDeepHash(self.uri);
  result = result * 31 + FLTPigeonDeepHash(self.packageName);
  result = result * 31 + FLTPigeonDeepHash(self.formatHint);
  result = result * 31 + FLTPigeonDeepHash(self.httpHeaders);
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTCreateMessage(asset: %@, uri: %@, packageName: %@, formatHint: %@, httpHeaders: %@)", self.asset, self.uri, self.packageName, self.formatHint, self.httpHeaders];
}
@end

@implementation FLTMixWithOthersMessage
+ (instancetype)makeWithMixWithOthers:(BOOL )mixWithOthers {
  FLTMixWithOthersMessage* pigeonResult = [[FLTMixWithOthersMessage alloc] init];
  pigeonResult.mixWithOthers = mixWithOthers;
  return pigeonResult;
}
+ (FLTMixWithOthersMessage *)fromList:(NSArray<id> *)list {
  FLTMixWithOthersMessage *pigeonResult = [[FLTMixWithOthersMessage alloc] init];
  pigeonResult.mixWithOthers = [GetNullableObjectAtIndex(list, 0) boolValue];
  return pigeonResult;
}
+ (nullable FLTMixWithOthersMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTMixWithOthersMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.mixWithOthers),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTMixWithOthersMessage *other = (FLTMixWithOthersMessage *)object;
  return self.mixWithOthers == other.mixWithOthers;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.mixWithOthers).hash;
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTMixWithOthersMessage(mixWithOthers: %@)", self.mixWithOthers ? @"true" : @"false"];
}
@end

@implementation FLTBufferMessage
+ (instancetype)makeWithTextureId:(NSInteger )textureId
    second:(NSInteger )second {
  FLTBufferMessage* pigeonResult = [[FLTBufferMessage alloc] init];
  pigeonResult.textureId = textureId;
  pigeonResult.second = second;
  return pigeonResult;
}
+ (FLTBufferMessage *)fromList:(NSArray<id> *)list {
  FLTBufferMessage *pigeonResult = [[FLTBufferMessage alloc] init];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.second = [GetNullableObjectAtIndex(list, 1) integerValue];
  return pigeonResult;
}
+ (nullable FLTBufferMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTBufferMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.textureId),
    @(self.second),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTBufferMessage *other = (FLTBufferMessage *)object;
  return self.textureId == other.textureId && self.second == other.second;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.textureId).hash;
  result = result * 31 + @(self.second).hash;
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTBufferMessage(textureId: %ld, second: %ld)", (long)self.textureId, (long)self.second];
}
@end

@implementation FLTMaxVideoResolutionMessage
+ (instancetype)makeWithTextureId:(NSInteger )textureId
    width:(NSInteger )width
    height:(NSInteger )height {
  FLTMaxVideoResolutionMessage* pigeonResult = [[FLTMaxVideoResolutionMessage alloc] init];
  pigeonResult.textureId = textureId;
  pigeonResult.width = width;
  pigeonResult.height = height;
  return pigeonResult;
}
+ (FLTMaxVideoResolutionMessage *)fromList:(NSArray<id> *)list {
  FLTMaxVideoResolutionMessage *pigeonResult = [[FLTMaxVideoResolutionMessage alloc] init];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.width = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.height = [GetNullableObjectAtIndex(list, 2) integerValue];
  return pigeonResult;
}
+ (nullable FLTMaxVideoResolutionMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTMaxVideoResolutionMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.textureId),
    @(self.width),
    @(self.height),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTMaxVideoResolutionMessage *other = (FLTMaxVideoResolutionMessage *)object;
  return self.textureId == other.textureId && self.width == other.width && self.height == other.height;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.textureId).hash;
  result = result * 31 + @(self.width).hash;
  result = result * 31 + @(self.height).hash;
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTMaxVideoResolutionMessage(textureId: %ld, width: %ld, height: %ld)", (long)self.textureId, (long)self.width, (long)self.height];
}
@end

@implementation FLTIsPlayingMessage
+ (instancetype)makeWithTextureId:(NSInteger )textureId
    isPlaying:(BOOL )isPlaying {
  FLTIsPlayingMessage* pigeonResult = [[FLTIsPlayingMessage alloc] init];
  pigeonResult.textureId = textureId;
  pigeonResult.isPlaying = isPlaying;
  return pigeonResult;
}
+ (FLTIsPlayingMessage *)fromList:(NSArray<id> *)list {
  FLTIsPlayingMessage *pigeonResult = [[FLTIsPlayingMessage alloc] init];
  pigeonResult.textureId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.isPlaying = [GetNullableObjectAtIndex(list, 1) boolValue];
  return pigeonResult;
}
+ (nullable FLTIsPlayingMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTIsPlayingMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.textureId),
    @(self.isPlaying),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FLTIsPlayingMessage *other = (FLTIsPlayingMessage *)object;
  return self.textureId == other.textureId && self.isPlaying == other.isPlaying;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.textureId).hash;
  result = result * 31 + @(self.isPlaying).hash;
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"FLTIsPlayingMessage(textureId: %ld, isPlaying: %@)", (long)self.textureId, self.isPlaying ? @"true" : @"false"];
}
@end

@interface FLTMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation FLTMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [FLTTextureMessage fromList:[self readValue]];
    case 130: 
      return [FLTLoopingMessage fromList:[self readValue]];
    case 131: 
      return [FLTVolumeMessage fromList:[self readValue]];
    case 132: 
      return [FLTPlaybackSpeedMessage fromList:[self readValue]];
    case 133: 
      return [FLTPositionMessage fromList:[self readValue]];
    case 134: 
      return [FLTDurationMessage fromList:[self readValue]];
    case 135: 
      return [FLTStartMessage fromList:[self readValue]];
    case 136: 
      return [FLTCreateMessage fromList:[self readValue]];
    case 137: 
      return [FLTMixWithOthersMessage fromList:[self readValue]];
    case 138: 
      return [FLTBufferMessage fromList:[self readValue]];
    case 139: 
      return [FLTMaxVideoResolutionMessage fromList:[self readValue]];
    case 140: 
      return [FLTIsPlayingMessage fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FLTMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation FLTMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[FLTTextureMessage class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTLoopingMessage class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTVolumeMessage class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTPlaybackSpeedMessage class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTPositionMessage class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTDurationMessage class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTStartMessage class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTCreateMessage class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTMixWithOthersMessage class]]) {
    [self writeByte:137];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTBufferMessage class]]) {
    [self writeByte:138];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTMaxVideoResolutionMessage class]]) {
    [self writeByte:139];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTIsPlayingMessage class]]) {
    [self writeByte:140];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FLTMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FLTMessagesPigeonCodecReaderWriter *readerWriter = [[FLTMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpFLTAVFoundationVideoPlayerApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTAVFoundationVideoPlayerApi> *api) {
  SetUpFLTAVFoundationVideoPlayerApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpFLTAVFoundationVideoPlayerApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTAVFoundationVideoPlayerApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.initialize", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(initialize:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(initialize:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api initialize:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.create", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(create:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(create:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTCreateMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        FLTTextureMessage *output = [api create:arg_msg error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.dispose", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(dispose:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(dispose:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTTextureMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api dispose:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.setLooping", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setLooping:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(setLooping:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTLoopingMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setLooping:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.setVolume", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setVolume:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(setVolume:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTVolumeMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setVolume:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.setPlaybackSpeed", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPlaybackSpeed:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(setPlaybackSpeed:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTPlaybackSpeedMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setPlaybackSpeed:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.play", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(play:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(play:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTTextureMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api play:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.position", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(position:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(position:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTTextureMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        FLTPositionMessage *output = [api position:arg_msg error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.duration", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(duration:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(duration:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTTextureMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        FLTDurationMessage *output = [api duration:arg_msg error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.start", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(start:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(start:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTTextureMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        FLTStartMessage *output = [api start:arg_msg error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.seekTo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(seekTo:completion:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(seekTo:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTPositionMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        [api seekTo:arg_msg completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.pause", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pause:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(pause:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTTextureMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api pause:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.setMixWithOthers", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMixWithOthers:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(setMixWithOthers:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTMixWithOthersMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setMixWithOthers:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.setBuffer", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setBuffer:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(setBuffer:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTBufferMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setBuffer:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.setMaxVideoResolution", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMaxVideoResolution:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(setMaxVideoResolution:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTMaxVideoResolutionMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setMaxVideoResolution:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.isPlaying", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isPlaying:error:)], @"FLTAVFoundationVideoPlayerApi api (%@) doesn't respond to @selector(isPlaying:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTTextureMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        FLTIsPlayingMessage *output = [api isPlaying:arg_msg error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
